apiVersion: v1
kind: Service
metadata:
  name: {{ include "sandbox-platform.fullname" . }}-frontend
  labels:
    {{- include "sandbox-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  selector:
    {{- include "sandbox-platform.selectorLabels" (dict "context" . "component" "frontend") | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.frontend.service.port }}
      targetPort: http
