apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sandbox-platform.fullname" . }}-frontend
  labels:
    {{- include "sandbox-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      {{- include "sandbox-platform.selectorLabels" (dict "context" . "component" "frontend") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "sandbox-platform.selectorLabels" (dict "context" . "component" "frontend") | nindent 8 }}
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
